### ISSUE TITLE
Sanity checks

### ISSUE THREAD

**Issue by mkrasmus** [PacktPublishing/Hands-On-Machine-Learning-Using-Amazon-SageMaker-v-#2]
Hi Pavlos, 

really enjoying the learning experience. 

Couple of things I've picked up. Running from within a company firewall that has made it difficult to install packages with Python via SSL (to create the environment) I've had to use conda to create an environment and follow your steps.

But as for an issue I've come across. I am unable to execute `estimator.fit(data_location)` in train_and_deploy_your_first_model_on_sagemaker. 

Instead I get the following:

`2019-03-07 05:16:57 Starting - Starting the training job...
2019-03-07 05:16:59 Starting - Launching requested ML instances...
2019-03-07 05:18:05 Starting - Preparing the instances for training......
2019-03-07 05:19:14 Downloading - Downloading input data
2019-03-07 05:19:14 Training - Downloading the training image
2019-03-07 05:19:14 Failed - Training job failed`

`print(estimator)` gives me `<sagemaker.estimator.Estimator object at 0x000000000A851DD8>`

But `estimator.fit(data_location)` results in `Failed Reason: ClientError: Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.`

**Comment by mkrasmus** [comment]
Ok just needed to follow along with more of the tutorial. The image just needed to be created locally for this to work.

**Comment by pm3310** [comment]
Hi @mkrasmus,

I'm very glad you're enjoying this course :-) 

Apologies for the late response but I was on holiday. I just came back. I'm happy that the issue has been resolved.

Please, feel free to create/raise any issue or PR in the future. 

Thanks,
Pavlos

**Comment by mkrasmus** [comment]
Hi Pavlos

I wanted to ask you about that first example. Because it worked for me in the end and I’d like to learn a little more about the technology that went into it.

What I think I lack the most is an understanding of Docker and Flask.

Do you have any suggestions on how to learn these two technologies, principally to create similar machine learning algorithms to deploy to Sagemaker. That is, just enough, not everything.

Is there a good book out there you would recommend? Or any other similar online learning module through Packt?

Thank you
Michael

**Comment by pm3310** [comment]
Hi Michael, 

Sure! This one https://docs.docker.com/get-started/ is very neat. You need only to understand parts 1 and 2. It combines Docker and a little bit of Flask.

For your purposes, the only thing that you need to understand is the concept of Routing at flask https://www.tutorialspoint.com/flask/flask_routing.htm

You can go very deep into Docker and Flask but you don't need to if you're only interested to deploy ML models :-) In this case, the whole purpose is to hide the details of Docker and Flask as much as possible. I've developed an open-source tool to use SageMaker by hiding even more details of Docker and Flask https://github.com/Kenza-AI/sagify 

Please, let me know if these resources were helpful to you. 

Thanks,
Pavlos

**Comment by mkrasmus** [comment]
Excellent you're awesome!
